# Generated by Django 4.2.8 on 2023-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default/profile_picture.png', null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
